import { motion } from 'framer-motion'
import { useVeritas } from '../App'
import Navbar from '../components/Navbar'

export default function Report() {
  const { filename, analysisData } = useVeritas()
  const score = analysisData?.integrity_score?.verified || 0

  const downloadReport = () => {
    const report = `
VERITAS RESEARCH INTEGRITY REPORT
Generated: ${new Date().toLocaleString()}
================================

PAPER: ${filename || 'Unknown'}
INTEGRITY SCORE: ${score}%

ANALYSIS SUMMARY
----------------
Verified: ${analysisData?.integrity_score?.verified || 0}%
Weak: ${analysisData?.integrity_score?.weak || 0}%
Hallucinated: ${analysisData?.integrity_score?.hallucinated || 0}%

MISSING TOPICS
--------------
${analysisData?.dna?.missing_topics?.join('\n') || 'Run DNA analysis first'}

FLAGGED SENTENCES
-----------------
${analysisData?.heatmap?.results?.filter(r => r.status === 'hallucinated')?.map(r => `• ${r.sentence}`)?.join('\n') || 'Run heatmap analysis first'}

================================
Generated by Veritas — Research Integrity Platform
    `.trim()

    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'veritas-integrity-report.txt'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div style={{ minHeight: '100vh', background: '#fafaf8', fontFamily: 'Inter, sans-serif' }}>
      <Navbar score={score} />
      <div style={{ padding: '80px 48px 48px', maxWidth: '800px', margin: '0 auto' }}>

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} style={{ marginBottom: '32px' }}>
          <p style={{ color: '#059669', fontSize: '13px', fontWeight: '700', letterSpacing: '0.1em', marginBottom: '8px' }}>EXPORT REPORT</p>
          <h1 style={{ fontSize: '32px', fontWeight: '800', color: '#1c1917', marginBottom: '8px' }}>
            Download Your Report 📑
          </h1>
          <p style={{ color: '#78716c', fontSize: '15px' }}>
            Export a complete integrity report with all analysis results.
          </p>
        </motion.div>

        {/* Report Preview */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          style={{
            background: '#fff', border: '1px solid #e7e5e4',
            borderRadius: '16px', padding: '32px', marginBottom: '20px',
            boxShadow: '0 1px 4px rgba(0,0,0,0.06)'
          }}>
          <p style={{ color: '#78716c', fontSize: '12px', fontWeight: '700', letterSpacing: '0.1em', marginBottom: '20px' }}>
            REPORT PREVIEW
          </p>

          {[
            { label: 'Paper', value: filename || 'Not uploaded', color: '#f97316' },
            { label: 'Integrity Score', value: `${score}%`, color: score > 75 ? '#059669' : '#ef4444' },
            { label: 'Verified Sentences', value: `${analysisData?.integrity_score?.verified || 0}%`, color: '#059669' },
            { label: 'Hallucinated', value: `${analysisData?.integrity_score?.hallucinated || 0}%`, color: '#ef4444' },
            { label: 'Missing Topics', value: analysisData?.dna?.missing_topics?.length || 0, color: '#d97706' },
          ].map((item, i) => (
            <div key={item.label} style={{
              display: 'flex', justifyContent: 'space-between',
              alignItems: 'center',
              borderBottom: i < 4 ? '1px solid #f3f4f6' : 'none',
              padding: '12px 0'
            }}>
              <span style={{ color: '#78716c', fontSize: '14px' }}>{item.label}</span>
              <span style={{ color: item.color, fontSize: '14px', fontWeight: '700' }}>{item.value}</span>
            </div>
          ))}
        </motion.div>

        <motion.button
          whileHover={{ scale: 1.02, boxShadow: '0 6px 20px rgba(5,150,105,0.3)' }}
          whileTap={{ scale: 0.98 }}
          onClick={downloadReport}
          style={{
            background: '#059669', color: 'white', border: 'none',
            padding: '14px 48px', borderRadius: '10px', cursor: 'pointer',
            fontWeight: '700', fontSize: '15px',
            boxShadow: '0 4px 12px rgba(5,150,105,0.25)',
            display: 'flex', alignItems: 'center', gap: '8px'
          }}>
          📑 Download Report
        </motion.button>

        <p style={{ color: '#9ca3af', fontSize: '13px', marginTop: '10px' }}>
          Run all analyses first for a complete report
        </p>
      </div>
    </div>
  )
}